config/routes.rb
Rails.application.routes.draw do
	root 'kittens#index'

	resources :kittens
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
	validates :name, presence: true
	validates :age, presence: true
	validates :cuteness, presence: true
	validates :softness, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def new
    @kitten = Kitten.new
  end

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.xml  { render xml: @kittens }
      format.json { render json: @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    flash[:success] = "Kitten deleted!"
    redirect_to kittens_path
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Kitten created!"
      redirect_to kittens_path
    else
      flash[:error] = @kitten.errors.full_messages
      redirect_to new_kitten_path
    end
  end

  def update
    @kitten = Kitten.find(params[:id])
    @kitten.update(kitten_params)
    if @kitten.valid?
      flash[:success] = "Kitten updated!"
      redirect_to @kitten
    else
      flash[:error] = @kitten.errors.full_messages
      redirect_to kittens_path
    end
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for @kitten do |f| %>
		Name: <%= f.text_field :name %><br>
		Age: <%= f.number_field :age %><br>
		Cuteness: <%= f.number_field :cuteness %><br>
		Softness: <%= f.number_field :softness %><br><br>
	
		<%= f.submit yield(:button_text) %>
<% end %>

app/views/kittens/create.html.erb
<h1>Kittens#create</h1>
<p>Find me in app/views/kittens/create.html.erb</p>

app/views/kittens/destroy.html.erb
<h1>Kittens#destroy</h1>
<p>Find me in app/views/kittens/destroy.html.erb</p>

app/views/kittens/edit.html.erb
<% provide(:button_text, "Update") %>
<h1>Edit Kitten</h1>
<p>
	<%= render "form" %>
</p>

app/views/kittens/index.html.erb
<h1>Kittens</h1>
<p>
	<% @kittens.each do |f| %>
		Name: <%= f.name %><br>
		Age: <%= f.age %><br>
		Cuteness: <%= f.cuteness %><br>
		Softness: <%= f.softness %><br>
		Link to <%= link_to "#{f.name}", f %><br>
		<%= link_to "Delete", kitten_path(f), method: :delete  %><br><br>
	<% end %>
</p>

app/views/kittens/new.html.erb
<% provide(:button_text, "Create kitten") %>
<h1>New Kitten</h1>
<p>
	<%= render "form" %>
</p>

app/views/kittens/show.html.erb
<h1>Show Kitten</h1>
<p>
	Id: <%= @kitten.id %><br>
	Name: <%= @kitten.name %><br>
	Age: <%= @kitten.age %><br>
	Cuteness: <%= @kitten.cuteness %><br>
	Softness: <%= @kitten.softness %><br><br>
</p>

app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
  <% flash.each do |f| %>
    <%= f %>
  <% end %>
  <body>
    <%= yield %>
  </body>
  <% if params[:action] == "show" && params[:controller] == "kittens" %>
    <%= link_to "Edit kitten", edit_kitten_url(@kitten) %>
    <%= link_to "Delete kitten", kitten_path(@kitten), method: :delete %>
  <% elsif params[:action] == "edit" && params[:controller] = "kittens" %>
    <%= link_to "Delete kitten", kitten_path(@kitten), method: :delete %>
  <% end %>
  <%= link_to "New kitten", new_kitten_path %>
  <%= link_to "Kittens", kittens_path %>
</html>